SITENAME="My Website"
SITEADDRESS=https://example.com
SITETITLE="My Personal Site"
SITEDESCRIPTION="My Personal Web Pages"
MAILTO=me@example.com
SHOWRECENTPOSTS="Yes"
SHOWMAILTO="Yes"

CATCOUNT=3
CAT1=ABOUT
CATNAME1="About Me"
CAT2=HOBBIES
CATNAME2="My Hobbies"
CAT3=EXAMPLE
CATNAME3="Example Category"
